# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeekAsia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 4.0.0-alpha.1'
  pod 'Bolts-Swift', '~> 1.3' # bolts for Swift

  # Pods for SeekAsia

end
